source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

inhibit_all_warnings!
#pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

target 'Shaolin' do
 
 
pod 'Masonry'

pod 'FMDB'

pod 'MJExtension'
pod 'AFNetworking','~>4.0'

#,'0.9.2'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'LGFFreePT','~>0.3.2'
pod 'TZImagePickerController'
pod 'FDFullscreenPopGesture'
pod 'MMPopupView'
pod 'XHLaunchAd', '~> 3.9.7'
pod 'AliPlayerSDK_iOS'



#Lite版本(不带实时音视频通话功能)
pod 'HyphenateLite'

pod 'SDWebImage', '~> 4.0'
#pod 'SDWebImage/GIF'

  target 'ShaolinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShaolinUITests' do
    # Pods for testing
  end

end
